### ISSUE TITLE
Icon not visible in Activity Bar after installation

### ISSUE THREAD

**Issue by RobJohnston** [microsoft/vscode-node-azure-pack#70]
Possibly relate to #61, but I'm running the latest version of VS Code.  After installing Azure Tools, its icon is not visible in the Activity Bar.

However, if I disable Azure Resources, then click "Restart Extensions", then click the "Enable" button, the icon will appear.  I can then enable all dependent extensions that were disabled when Azure Resources was disabled.

But then by closing or opening a folder, or restarting VS Code, I have to do the process all over again.

**Comment by alexweininger** [comment]
That's very weird. Are there any errors anywhere when installing? If you could provide a video that would also be helpful.

**Comment by RobJohnston** [comment]
I didn't see any errors, but I'm a relatively naive user of VS Code.  How's this for a video (see attached):

https://github.com/user-attachments/assets/add528f1-5b99-4a46-b902-45f565f78563

In this video, I'm showing the version of VS Code (1.95.3 on Windows 11).  All extensions installed are checked.  But Azure Tools is installed already, so I disable Azure Resources.  After re-enabling it, the Azure icon appears! I then re-enable all other Azure extensions that were disabled when I disabled Azure Tools.  Finally, I open a folder and the icon disappears again.

Would this output from the "Extension Host" be relevant? 

2024-11-17 18:02:51.534 [info] Extension host with pid 31644 started
2024-11-17 18:02:51.535 [info] Skipping acquiring lock for c:\Users\rob_j\AppData\Roaming\Code\User\workspaceStorage\54228756b24706cd89663ad37f44e0c2.
2024-11-17 18:02:51.938 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-17 18:02:52.065 [info] ExtensionService#_doActivateExtension adrianwilczynski.namespace, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:02:52.098 [info] ExtensionService#_doActivateExtension jesschadwick.nuget-reverse-package-search, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:02:56.418 [info] Extension host with pid 23852 started
2024-11-17 18:02:57.026 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-11-17 18:02:57.714 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-17 18:02:57.774 [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense, startup: true, activationEvent: '*'
2024-11-17 18:02:59.054 [info] ExtensionService#_doActivateExtension EditorConfig.EditorConfig, startup: true, activationEvent: '*'
2024-11-17 18:02:59.992 [info] ExtensionService#_doActivateExtension HelloCognition.hello-code-snippets, startup: true, activationEvent: '*'
2024-11-17 18:03:00.124 [info] ExtensionService#_doActivateExtension ybaumes.highlight-trailing-white-spaces, startup: true, activationEvent: '*'
2024-11-17 18:03:00.272 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-17 18:03:00.469 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime, startup: false, activationEvent: 'onLanguage:csharp', root cause: josefpihrt-vscode.roslynator
2024-11-17 18:03:00.559 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-17 18:03:00.679 [info] ExtensionService#_doActivateExtension k--kato.docomment, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:03:00.708 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-11-17 18:03:00.779 [info] Extension host terminating: renderer closed the MessagePort
2024-11-17 18:03:00.787 [info] Extension host with pid 31644 exiting with code 0
2024-11-17 18:03:00.965 [info] Eager extensions activated
2024-11-17 18:03:00.975 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:03:00.997 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:03:01.032 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:03:01.943 [info] ExtensionService#_doActivateExtension ecmel.vscode-html-css, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:03:01.969 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:03:02.096 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:03:02.594 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:03:02.798 [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:03:03.731 [info] ExtensionService#_doActivateExtension vscode-icons-team.vscode-icons, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:04:55.081 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-17 18:05:21.241 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azureresourcegroups, startup: false, activationEvent: 'onView:azureResourceGroups'
2024-11-17 18:05:22.285 [info] ExtensionService#_doActivateExtension ms-azuretools.azure-dev, startup: false, activationEvent: 'api', root cause: ms-azuretools.vscode-azureresourcegroups
2024-11-17 18:05:22.600 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2024-11-17 18:05:32.758 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azurestorage, startup: false, activationEvent: 'onView:azureWorkspace'
2024-11-17 18:05:38.329 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-cosmosdb, startup: false, activationEvent: 'onView:azureWorkspace'
2024-11-17 18:05:41.722 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azurefunctions, startup: false, activationEvent: 'onView:azureWorkspace'
2024-11-17 18:06:27.814 [info] Extension host terminating: renderer closed the MessagePort
2024-11-17 18:06:28.218 [error] Canceled: Canceled
	at new tT (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:108738)
	at py.U (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113348)
	at s.<computed>.n.charCodeAt.s.<computed> (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110842)
	at Y0.g (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32313)
	at Y0.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31817)
	at r.registerCommand.description (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31147)
	at Y0.h (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
	at Y0.g (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31910)
	at Y0.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31817)
	at Object.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:37246)
	at f (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1482:14096)
	at c (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1482:18656)
	at ActionRunners._updateContextKeys (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:65661)
	at s (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:64105)
	at RegisteredActionRunner.unregister (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:64248)
	at RegisteredActionRunner.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:62902)
	at ActionRunners.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:63688)
	at c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1428:14975
	at Array.forEach (<anonymous>)
	at Object.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1428:14957)
	at ci (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:699)
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14992
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:1009
	at Object.dispose (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:2146)
	at z_.eb (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:11919)
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9874
	at Array.map (<anonymous>)
	at z_.$ (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9862)
	at z_.terminate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10105)
	at EC.terminate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:1424)
	at Zi (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:15084)
	at MessagePortMain.<anonymous> (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11632)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) setContext undefined
2024-11-17 18:06:28.219 [error] Canceled: Canceled
	at new tT (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:108738)
	at py.U (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113348)
	at s.<computed>.n.charCodeAt.s.<computed> (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110842)
	at Y0.g (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32313)
	at Y0.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31817)
	at r.registerCommand.description (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31147)
	at Y0.h (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
	at Y0.g (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31910)
	at Y0.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31817)
	at Object.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:37246)
	at f (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1482:14096)
	at c (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1482:18656)
	at ActionRunners._updateContextKeys (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:65661)
	at s (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:64105)
	at RegisteredActionRunner.unregister (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:64248)
	at RegisteredActionRunner.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:62902)
	at ActionRunners.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:63688)
	at c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1428:14975
	at Array.forEach (<anonymous>)
	at Object.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1428:14957)
	at ci (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:699)
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14992
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:1009
	at Object.dispose (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:2146)
	at z_.eb (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:11919)
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9874
	at Array.map (<anonymous>)
	at z_.$ (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9862)
	at z_.terminate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10105)
	at EC.terminate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:1424)
	at Zi (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:15084)
	at MessagePortMain.<anonymous> (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11632)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) setContext undefined
2024-11-17 18:06:28.220 [error] Canceled: Canceled
	at new tT (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:108738)
	at py.U (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113348)
	at s.<computed>.n.charCodeAt.s.<computed> (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110842)
	at Y0.g (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32313)
	at Y0.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31817)
	at r.registerCommand.description (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31147)
	at Y0.h (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
	at Y0.g (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31910)
	at Y0.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31817)
	at Object.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:37246)
	at f (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1482:14096)
	at c (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1482:18656)
	at ActionRunners._updateContextKeys (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:65661)
	at s (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:64105)
	at RegisteredActionRunner.unregister (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:64248)
	at RegisteredActionRunner.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:62902)
	at ActionRunners.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1107:63688)
	at c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1428:14975
	at Array.forEach (<anonymous>)
	at Object.dispose (c:\Users\rob_j\.vscode\extensions\eamodio.gitlens-16.0.1\dist\gitlens.js:1428:14957)
	at ci (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:699)
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14992
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:1009
	at Object.dispose (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:2146)
	at z_.eb (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:11919)
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9874
	at Array.map (<anonymous>)
	at z_.$ (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9862)
	at z_.terminate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10105)
	at EC.terminate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:1424)
	at Zi (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:15084)
	at MessagePortMain.<anonymous> (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11632)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) setContext undefined
2024-11-17 18:06:28.224 [info] Extension host with pid 23852 exiting with code 0
2024-11-17 18:06:32.047 [info] Extension host with pid 31340 started
2024-11-17 18:06:32.047 [info] Skipping acquiring lock for c:\Users\rob_j\AppData\Roaming\Code\User\workspaceStorage\54228756b24706cd89663ad37f44e0c2.
2024-11-17 18:06:32.336 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-17 18:06:32.423 [info] ExtensionService#_doActivateExtension adrianwilczynski.namespace, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:06:32.430 [info] ExtensionService#_doActivateExtension jesschadwick.nuget-reverse-package-search, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:06:32.949 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime, startup: false, activationEvent: 'onLanguage:csharp', root cause: josefpihrt-vscode.roslynator
2024-11-17 18:06:33.450 [info] ExtensionService#_doActivateExtension k--kato.docomment, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:06:33.698 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-17 18:06:33.705 [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense, startup: true, activationEvent: '*'
2024-11-17 18:06:33.736 [info] ExtensionService#_doActivateExtension EditorConfig.EditorConfig, startup: true, activationEvent: '*'
2024-11-17 18:06:33.773 [info] ExtensionService#_doActivateExtension HelloCognition.hello-code-snippets, startup: true, activationEvent: '*'
2024-11-17 18:06:33.783 [info] ExtensionService#_doActivateExtension ybaumes.highlight-trailing-white-spaces, startup: true, activationEvent: '*'
2024-11-17 18:06:34.071 [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: false, activationEvent: 'onLanguage:csharp', root cause: josefpihrt-vscode.roslynator
2024-11-17 18:06:36.349 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-17 18:06:37.230 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-17 18:06:38.454 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-11-17 18:06:38.789 [info] ExtensionService#_doActivateExtension josefpihrt-vscode.roslynator, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:06:41.210 [info] ExtensionService#_doActivateExtension ms-dotnettools.csdevkit, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:06:42.342 [info] ExtensionService#_doActivateExtension formulahendry.dotnet-test-explorer, startup: true, activationEvent: 'workspaceContains:**/*.csproj,**/*.fsproj'
2024-11-17 18:06:58.746 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azureresourcegroups, startup: true, activationEvent: 'workspaceContains:**/host.json', root cause: ms-azuretools.vscode-azurefunctions
2024-11-17 18:06:59.782 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:06:59.822 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:06:59.870 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:07:00.331 [info] ExtensionService#_doActivateExtension ecmel.vscode-html-css, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:07:00.387 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:07:00.873 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:07:01.026 [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:07:01.289 [info] ExtensionService#_doActivateExtension vscode-icons-team.vscode-icons, startup: false, activationEvent: 'onStartupFinished'
2024-11-17 18:07:01.429 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-azurefunctions, startup: true, activationEvent: 'workspaceContains:**/host.json'
2024-11-17 18:07:03.903 [info] Eager extensions activated
2024-11-17 18:07:03.935 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscodeintellicode-csharp, startup: false, activationEvent: 'onLanguage:csharp'
2024-11-17 18:07:11.431 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2024-11-17 18:07:50.708 [error] Error: Timeout. Client cound not connect to server via named pipe
	at K.<anonymous> (c:\Users\rob_j\.vscode\extensions\ms-dotnettools.csharp-2.55.29-win32-x64\dist\extension.js:2:1178863)
	at Generator.next (<anonymous>)
	at s (c:\Users\rob_j\.vscode\extensions\ms-dotnettools.csharp-2.55.29-win32-x64\dist\extension.js:2:1164913)
